Resources:
  createpdfServiceRole16894455:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: create-pdf/create-pdf/ServiceRole/Resource
  createpdf03E616B9:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-312640258781-ap-southeast-2
        S3Key: f49ddea59270bb8fff3575f95f4f1ed8baa10c9d134ada08937f52988f1d48d8.zip
      Role:
        Fn::GetAtt:
          - createpdfServiceRole16894455
          - Arn
      Environment:
        Variables:
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
      Handler: index.main
      MemorySize: 1024
      Runtime: nodejs14.x
      Timeout: 20
    DependsOn:
      - createpdfServiceRole16894455
    Metadata:
      aws:cdk:path: create-pdf/create-pdf/Resource
      aws:asset:path: /Users/ian/dev/work/linz/html-pdf-lambda-cdk/cdk.out/asset.f49ddea59270bb8fff3575f95f4f1ed8baa10c9d134ada08937f52988f1d48d8
      aws:asset:is-bundled: true
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/zWNzQqDMBCEn8V73DYKvddCjz3oA4Q1bmX9ScBN2oP47o1KTx8zDN8UUGjQGX4lt92YT9zC2gS0o0qVWSec2w6N8x0NAq8Dz+hsYO8U4wxr7SdSj7fbuSkpDYpQELjvSBmqaEcKFQqp0wZp/Xds6tilx55df3hIfFxscu2nMMjlo2+gS7hmgzDnS3SBZ4L65A/Y/bDvwAAAAA==
    Metadata:
      aws:cdk:path: create-pdf/CDKMetadata/Default
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

